# Generated by Django 3.2.6 on 2021-09-19 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='qwe', max_length=255)),
                ('text', models.TextField(default='qwe')),
                ('published_date', models.DateTimeField(default=datetime.datetime(2021, 9, 19, 17, 21, 46, 394624, tzinfo=utc))),
            ],
        ),
    ]
